#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (52.55%)
# Total Accepted:    132.7K
# Total Submissions: 252.3K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution:
    def findTheDifference(self, s: 'str', t: 'str') -> 'str':
        hm = collections.defaultdict(int)
        for c in s:
            hm[c] += 1
        for c in t:
            hm[c] -= 1
            if hm[c] < 0:
                return c
        return s[0]
        
